### PR TITLE
Update to 0.14.0 for gtk-rs 0.14.0 and regenerate from Soup-2.4.gir

### PR DESCRIPTION
**Pull request by decathorpe**
This PR is my attempt at #23
This is the first time I have worked with a Rust project based on GObject Introspection stuff, so please bear with me.

I tried to follow the GIR book and these steps:

- installed gir from git and checked out gir-files repo
- renamed gir-soup.toml to Gir.toml to match other crates in the ecosystem
- regenerated all files with `gir -m sys -d ../gir-files/ -o .`
- added back libc::sockaddr import where it's missing
- updated crate version to 0.14.0 to match other recent crate releases in the ecosystem

The glib-sys, gio-sys and gobject-sys dependencies pointed to git repositories, which made `cargo package` fail, so I replaced those with the actual versions. Not sure if this is desirable or not ... but otherwise the crate won't be able to be published to crates.io, I think.

The regenerated files compile fine, but there is one test failure:

```
---- cross_validate_constants_with_c stdout ----
Constant value mismatch for SOUP_COOKIE_MAX_AGE_ONE_DAY
Rust: "0"
C:    "86400"
Constant value mismatch for SOUP_COOKIE_MAX_AGE_ONE_WEEK
Rust: "0"
C:    "604800"
Constant value mismatch for SOUP_COOKIE_MAX_AGE_ONE_YEAR
Rust: "0"
C:    "31556926.080000"
thread 'cross_validate_constants_with_c' panicked at 'FAILED: 358 passed; 3 failed', tests/abi.rs:110:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Not sure why those constants are zeroes on the Rust side.

### CODE REVIEW

**Comment by decathorpe** [comment]
I was able to build other packages against this version (i.e. webkit2gtk{,-sys} with the soup-sys dependency bumped to 0.14) and newsflash (which uses the webkit2gtk crate) successfully, so it looks like there's no unexpected breakage with my changes.

**Comment by antoyo** [comment]
Hmm…

One thing I forgot to tell you is that the branch `crate` is what end up being published on `crates.io`. Maybe this branch won't have this constant issue if you try regenerating from Gir?

Otherwise, I don't know.

@sdroege @bilelmoussaoui Any ideas?

**Comment by decathorpe** [comment]
Ok, I didn't know that. I can revert the change from "version" to "git" dependencies for the -sys crates.

**Comment by antoyo** [comment]
Oh, I meant you should use the `crate` branch instead of the master branch (if you want it to be published on crates.io).

The master branch is the development version and the crate branch is the one being published.

**Comment by decathorpe** [comment]
Well, shouldn't this change land in both branches then? I don't particularly care about how your release process works.

**Comment by antoyo** [comment]
You can make 2 PRs if you want, but that's more work :) .

Because of how these branches were made, we cannot just merge one into the other.

**Comment by sdroege** [comment]
The constant issue is a bug in the .gir file:

```xml
    <constant name="COOKIE_MAX_AGE_ONE_DAY"
              value="0"
              c:type="SOUP_COOKIE_MAX_AGE_ONE_DAY"
              version="2.24">
      <doc xml:space="preserve"
           filename="../libsoup/soup-cookie.c"
           line="587">A constant corresponding to 1 day, for use with soup_cookie_new()
and soup_cookie_set_max_age().</doc>
      <source-position filename="../libsoup/soup-cookie.h" line="42"/>
      <type name="gint" c:type="gint"/>
    </constant>
```

As it's a calculation in the header file, gobject-introspection can't parse it properly. This needs a `(value ...)` annotation or be written as a plain number in the header file.

**Comment by decathorpe** [comment]
Ok, I just checked, the constants test already fails without my changes, so this issue has been present for a while. in fact, checking with git blame, those constants were wrong on the Rust side since "Initial commit" https://github.com/gtk-rs/soup-sys-rs/commit/a18fb227d31fc1c537d274d878ff0c99a61bd087

Does this block my PR? Or where should this be fixed?

**Comment by antoyo** [comment]
Oh, it's okay, then. I forgot there's no CI on this repo.

**Comment by decathorpe** [comment]
Is there something I can do to move this forward? Does the .gir file need to be fixed somehow?

Even if you won't accept this exact patch and do the changes yourselves, it would be great to have the soup-sys crate updated (and bump the dependency in webkit2gtk{,-sys} to match).

I have already temporarily applied the patch from this PR to Fedora builds of the soup-sys crate, and I have encountered no problems with it, but I dislike diverging from upstream projects for long stretches of time.

**Comment by antoyo** [comment]
I can't remember if there's an option to override a value in the `gir` file. Maybe look [here](https://gtk-rs.org/gir/book/config_ffi.html) to check.

Otherwise, I'll accept the PR with a manual fix (in an extra commit). Can you please do either of those?

(As a reminder, you'll also need to make a PR for the `crate` branch so that I can deploy it on crates.io.)

**Comment by decathorpe** [comment]
The `master` and `crate` branches have seemingly diverged. How do I know which changes from `master` I need to include in the new PR? Or should changes from the `crate` branch be merged into `master` first`? Sorry, I find your development / release process very confusing.

**Comment by antoyo** [comment]
Yeah, it is confusing, sorry about that.
What I usually do is to generate the code again in the crate branch; so there are no merge from one to the other.

If that can be fixed to just use normal merges, that would be great.

**Pull request closed without merging**
