### PR TITLE
Update for gtk-rs 0.14.0 and regenerate from Gir

### PR DESCRIPTION
**Pull request by decathorpe**
This commit also contains some changes that have only been present in the master branch and not the "crate" branch until now.

This PR is a follow-up for https://github.com/gtk-rs/soup-sys-rs/pull/24.

Please cross-reference if I made any mistakes, or accidentally introduced (or reverted changes) compared to the master branch.

### CODE REVIEW

**Comment by decathorpe** [comment]
As mentioned in the other PR, the `cross_validate_constants_with_c` test fails due to issues in the Soup-2.4.gir file. It might be a good idea to fix that and set up CI in this repository?

**Comment by antoyo** [comment]
For the CI, can you try pushing again? I've just enabled it [there](https://app.travis-ci.com/github/antoyo/soup-sys-rs).
If you would be interested in switching to GitHub Actions, a PR would be appreciated :) .
When either of those works, you would be able to add a way to run the missing test if needed.

If you want, you can do a manual fix for the issue (in a separate commit).

Thanks!

**Review by antoyo — APPROVED** [review]
LGTM

**Comment by decathorpe** [comment]
I've pushed a small fix (cleaned up a leftover file).

But I'm not sure how to fix the SOUP_COOKIE_MAX_AGE_ONE_DAY / WEEK / YEAR issue, since I don't see where those constants are defined on the C side. Additionally, what I find very weird, is that SOUP_COOKIE_MAX_AGE_ONE_YEAR is defined as a `gint` / `c_int`, but the expected value turns out to be a floating point number (??)

**Comment by decathorpe** [comment]
PS: Did you actually enable Jenkins for this repository, or for your personal fork? The URL you pasted above makes me think you did the latter.

**Comment by antoyo** [comment]
Ooops, you're right.
The gtk-rs org won't enable Travis as they use GitHub Actions now, so if you really want CI, I encourage you to open a PR to add the necessary file.

So, do we merge this PR as is?

**Comment by antoyo** [comment]
@decathorpe: Since there has been no maintainer for these projects for a while, the repositories related to webkit2gtk-rs (including this one) will be archived in this organization.
One idea would be to move them to https://gitlab.gnome.org/World/Rust. Would you be interested in maintaining those?

**Comment by decathorpe** [comment]
Not really ...  I am only distantly interested in keeping them working because they're dependencies of newsflash (news_flash_gtk), for which we maintain an RPM package in Fedora. But if those crates get deprecated we'll probably just drop all of them, because we can't invest time to keep them alive due to lack of manpower

**Comment by antoyo** [comment]
@decathorpe : So, what do I do?
Can we just archive those repos?

**Comment by decathorpe** [comment]
If there's nobody to maintain them, then I don't have any objections to adding a deprecation notice to those projects' README files and archiving them. Dependent crates will probably have to find alternatives, then.

**Pull request closed without merging**
